# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glyph/worker/worker_protocol.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'glyph/worker/worker_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"glyph/worker/worker_protocol.proto\x12\x0c\x62laze.worker\"%\n\x05Input\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\x0c\"\x91\x01\n\x0bWorkRequest\x12\x11\n\targuments\x18\x01 \x03(\t\x12#\n\x06inputs\x18\x02 \x03(\x0b\x32\x13.blaze.worker.Input\x12\x12\n\nrequest_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x63\x61ncel\x18\x04 \x01(\x08\x12\x11\n\tverbosity\x18\x05 \x01(\x05\x12\x13\n\x0bsandbox_dir\x18\x06 \x01(\t\"\\\n\x0cWorkResponse\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\x05\x12\x15\n\rwas_cancelled\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glyph.worker.worker_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUT']._serialized_start=52
  _globals['_INPUT']._serialized_end=89
  _globals['_WORKREQUEST']._serialized_start=92
  _globals['_WORKREQUEST']._serialized_end=237
  _globals['_WORKRESPONSE']._serialized_start=239
  _globals['_WORKRESPONSE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
