load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(":toolchain.bzl", "GLYPH_TOOLCHAIN_TYPE", "glyph_toolchain")

package(default_visibility = ["//visibility:private"])

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

glyph_toolchain(
    name = "source_toolchain_impl",
    compiler = "//compiler:glyphc",
    worker = "//glyph/worker:worker",
)

toolchain(
    name = "source_toolchain",
    toolchain = ":source_toolchain_impl",
    toolchain_type = GLYPH_TOOLCHAIN_TYPE,
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "toolchain_bzl",
    srcs = ["toolchain.bzl"],
    visibility = ["//visibility:public"],
)
